-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 14:57:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema elearning_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elearning_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearning_app` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `elearning_app` ;

-- -----------------------------------------------------
-- Table `elearning_app`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon` VARCHAR(20) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cate_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `discout` INT NULL DEFAULT NULL,
  `hour_count` INT NULL DEFAULT NULL,
  `last_update` VARCHAR(255) NULL DEFAULT NULL,
  `letures_count` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `promotion_price` FLOAT NULL DEFAULT NULL,
  `view_count` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlu4ce0f8di1r2c4txhlav2v27` (`cate_id` ASC) VISIBLE,
  CONSTRAINT `FKlu4ce0f8di1r2c4txhlav2v27`
    FOREIGN KEY (`cate_id`)
    REFERENCES `elearning_app`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`tergets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`tergets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKi09matrkbcmf9o4nhroe190ki` (`course_id` ASC) VISIBLE,
  CONSTRAINT `FKi09matrkbcmf9o4nhroe190ki`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `elearning_app`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`user_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`user_course` (
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `FKf4qni5wnlq0x70fm39w9tv7x4` (`course_id` ASC) VISIBLE,
  INDEX `FKoc4yl478i6o8hf240vumhjgrb` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKf4qni5wnlq0x70fm39w9tv7x4`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`),
  CONSTRAINT `FKoc4yl478i6o8hf240vumhjgrb`
    FOREIGN KEY (`user_id`)
    REFERENCES `elearning_app`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `elearning_app`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL DEFAULT NULL,
  `time_count` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrccvc1a5qx2dqsyienwhuk66j` (`course_id` ASC) VISIBLE,
  CONSTRAINT `FKrccvc1a5qx2dqsyienwhuk66j`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
